version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: crypt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ZJ+G@%:qck4'[h}z,#?V2]
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crypt"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      INIT_TOKEN: gX2u0fCMNk6j4yJExZ54BuJKGK0Q0ZBn
      ADMIN_TOKEN: 
      POSTGRES_DB: crypt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ZJ%2BG%40%25%3Aqck4%27%5Bh%7Dz%2C%23%3FV2%5D
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
volumes:
  postgres:
